from enum import Enum


class VolumeStatus(Enum):
    CREATING = "CREATING"
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    ATTACHING = "ATTACHING"
    DETACHING = "DETACHING"
    IN_USE = "IN_USE"
    MAINTENANCE = "MAINTENANCE"
    DELETING = "DELETING"
    AWAITING_TRANSFER = "AWAITING_TRANSFER"
    ERROR = "ERROR"
    ERROR_DELETING = "ERROR_DELETING"
    BACKING_UP = "BACKING_UP"
    RESTORING_BACKUP = "RESTORING_BACKUP"
    ERROR_BACKING_UP = "ERROR_BACKING_UP"
    ERROR_RESTORING = "ERROR_RESTORING"
    ERROR_EXTENDING = "ERROR_EXTENDING"
    DOWNLOADING = "DOWNLOADING"
    UPLOADING = "UPLOADING"
    RETYPING = "RETYPING"
    EXTENDING = "EXTENDING"
